services:
  ansible-controller:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    container_name: ansible_controller
    volumes:
      - ./ansible:/etc/ansible
    networks:
      - ansible_net
    tty: true
    # Temporarily relaxed security for testing
    # security_opt:
    #   - no-new-privileges:true
    # read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    # cap_drop:
    #   - ALL
    command: /bin/bash -c "tail -f /dev/null"

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node1
    expose:
      - "22"
    networks:
      - ansible_net
    # Temporarily relaxed security for testing
    # security_opt:
    #   - no-new-privileges:true
    # cap_drop:
    #   - ALL
    # Only minimal capabilities needed for SSH
    # cap_add:
    #   - NET_BIND_SERVICE

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node2
    expose:
      - "22"
    networks:
      - ansible_net
    # Temporarily relaxed security for testing
    # security_opt:
    #   - no-new-privileges:true
    # cap_drop:
    #   - ALL
    # Only minimal capabilities needed for SSH
    # cap_add:
    #   - NET_BIND_SERVICE

networks:
  ansible_net:
    driver: bridge
