---
# Secrets directory & files
- name: Create secrets directory for compose
  ansible.builtin.file:
    path: "{{ docker_compose_path }}/secrets"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0700"
  tags: [wordpress, secrets]

- name: Write MySQL root password secret file
  ansible.builtin.copy:
    dest: "{{ docker_compose_path }}/secrets/mysql_root_password"
    content: "{{ mysql_root_password | default('') }}\n"
    owner: "www-data"
    group: "www-data"
    mode: "0600"
  no_log: true
  tags: [wordpress, secrets]

- name: Write MySQL user password secret file
  ansible.builtin.copy:
    dest: "{{ docker_compose_path }}/secrets/mysql_password"
    content: "{{ mysql_password | default('') }}\n"
    owner: "www-data"
    group: "www-data"
    mode: "0600"
  no_log: true
  tags: [wordpress, secrets]
