- name: Create Docker Compose directory
  ansible.builtin.file:
    path: "{{ docker_compose_path }}"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0755"
  become: true
  register: wordpress_compose_dir_result
  tags:
    - wordpress
    - directory
    - create

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0644"
  become: true
  register: wordpress_compose_file_result
  tags:
    - wordpress
    - templates

- name: Copy Nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ docker_compose_path }}/nginx.conf"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0644"
  become: true
  register: wordpress_nginx_config_result
  tags:
    - wordpress
    - nginx
    - templates

- name: Create certs directory for bootstrap
  ansible.builtin.file:
    path: "/etc/letsencrypt/live/{{ project_domain }}"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0755"
  become: true
  tags:
    - wordpress
    - certs

- name: Generate dummy self-signed certificate if none exists
  ansible.builtin.command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
      -keyout /etc/letsencrypt/live/{{ project_domain }}/privkey.pem
      -out /etc/letsencrypt/live/{{ project_domain }}/fullchain.pem
      -subj "/CN={{ project_domain }}"
  args:
    creates: "/etc/letsencrypt/live/{{ project_domain }}/fullchain.pem"
  become: true
  tags:
    - wordpress
    - certs

- name: Start Docker Compose services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}"
    state: present # present (compose up), absent (compose down), stopped (compose stop), restarted (compose restart)
  become: true
  become_user: "{{ project_user }}"
  register: wordpress_compose_up_result
  tags:
    - wordpress
    - docker-compose

# - name: Wait for MySQL container to be healthy
#   community.docker.docker_container:
#     name: "{{ mysql_container_name }}"
#     state: started
#     healthy_wait_timeout: 300 # Wait up to 5 minutes for MySQL to be healthy
#   become: true
#   become_user: "{{ project_user }}"
#   register: wordpress_mysql_health_check
#   tags:
#     - wordpress
#     - mysql
#     - health-check

- name: Wait for WordPress container to be healthy
  community.docker.docker_container:
    name: "{{ wordpress_container_name }}"
    state: started
    healthy_wait_timeout: 300 # Wait up to 5 minutes for WordPress to be healthy
  become: true
  become_user: "{{ project_user }}"
  register: wordpress_health_check
  tags:
    - wordpress
    - health-check

- name: Fix permissions on subdirectory
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: bash -lc 'chown -R www-data:www-data /var/www/html/wordpress'
    user: "www-data"
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - permissions

- name: Check if WP-CLI is already installed
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: wp --version
    user: "www-data"
  register: wordpress_cli_check
  failed_when: false
  changed_when: false
  become: true
  tags:
    - wordpress
    - wp-cli
    - check

- name: Install WP-CLI inside WordPress container
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  when: wordpress_cli_check.rc != 0
  tags:
    - wordpress
    - wp-cli
    - install

- name: Make WP-CLI executable
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: chmod +x wp-cli.phar
  when: wordpress_cli_check.rc != 0
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - install

- name: Move WP-CLI to PATH
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: mv wp-cli.phar /usr/local/bin/wp
  when: wordpress_cli_check.rc != 0
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - install

- name: Check if WordPress is already installed
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: wp core is-installed --path=/var/www/html/wordpress
    user: "www-data"
  register: wordpress_is_installed
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - install

- name: Install WordPress
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      bash -lc "wp core install
      --url=https://{{ project_domain }}/wordpress
      --title='{{ project_name }}'
      --admin_user='{{ wordpress_admin_user }}'
      --admin_password='{{ wordpress_admin_password }}'
      --admin_email='{{ wordpress_admin_email }}'
      --path=/var/www/html/wordpress"
    user: "www-data"
  when: wordpress_is_installed.rc != 0
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - install

################################################################################
# WordPress content setup (Home page + Front page + optional Site Icon)
################################################################################

- name: Lookup existing Home page ID by slug
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      bash -lc "wp post list --post_type=page --pagename=home --field=ID --path=/var/www/html/wordpress"
    user: "www-data"
  register: wordpress_home_lookup
  changed_when: false
  failed_when: false
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - content

- name: Create Home page if missing
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      wp post create
        --post_type=page
        --post_title='{{ wordpress_home_title }}'
        --post_name=home
        --post_status=publish
        --porcelain
        --path=/var/www/html/wordpress
    user: "www-data"
  when: (wordpress_home_lookup.stdout | trim) == ""
  register: wordpress_home_create
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - content

- name: Determine Home page ID
  ansible.builtin.set_fact:
    wordpress_home_page_id: >-
      {{ (wordpress_home_lookup.stdout | trim) if (wordpress_home_lookup.stdout | trim) != '' else (wordpress_home_create.stdout | trim) }}
  tags:
    - wordpress
    - wp-cli
    - content

- name: Update Home page content
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      bash -lc "wp post update {{ wordpress_home_page_id }}
      --post_content={{ wordpress_home_content | quote }}
      --path=/var/www/html/wordpress"
    user: "www-data"
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - content

- name: Set front page to display a static page
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      wp option update show_on_front page --path=/var/www/html/wordpress
    user: "www-data"
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - content

- name: Set Home page as the front page
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      wp option update page_on_front {{ wordpress_home_page_id }} --path=/var/www/html/wordpress
    user: "www-data"
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - content

- name: Check if site icon is already set
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      wp option get site_icon --path=/var/www/html/wordpress
    user: "www-data"
  register: wordpress_site_icon_option
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - content

- name: Copy site icon to remote host temp (if provided)
  ansible.builtin.copy:
    src: "{{ wordpress_site_icon_src }}"
    dest: "/tmp/icon.png"
    mode: "0644"
  when: (wordpress_site_icon_src | default('')) != '' and (wordpress_site_icon_option.stdout | trim) in ['', '0']
  become: true
  tags:
    - wordpress
    - wp-cli
    - content

- name: Copy site icon into WordPress container (docker cp)
  ansible.builtin.command: >
    docker cp /tmp/icon.png {{ wordpress_container_name }}:/tmp/icon.png
  when: (wordpress_site_icon_src | default('')) != '' and (wordpress_site_icon_option.stdout | trim) in ['', '0']
  changed_when: true
  become: true
  tags:
    - wordpress
    - wp-cli
    - content

- name: Import site icon into WordPress and set option
  community.docker.docker_container_exec:
    container: "{{ wordpress_container_name }}"
    command: >
      bash -lc 'icon_id=$(wp media import /tmp/icon.png --title="Favicon" --alt="Site Favicon"
      --porcelain --path=/var/www/html/wordpress) &&
      wp option update site_icon "$icon_id" --path=/var/www/html/wordpress'
    user: "www-data"
  when: (wordpress_site_icon_src | default('')) != '' and (wordpress_site_icon_option.stdout | trim) in ['', '0']
  become: true
  become_user: "{{ project_user }}"
  tags:
    - wordpress
    - wp-cli
    - content
