- name: Create Docker Compose directory
  ansible.builtin.file:
    path: "{{ docker_compose_path }}"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0755"
  become: true
  register: wordpress_compose_dir_result
  tags:
    - wordpress
    - directory
    - create

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yml"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0644"
  become: true
  register: wordpress_compose_file_result
  tags:
    - wordpress
    - templates

- name: Copy Nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ docker_compose_path }}/nginx.conf"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: "0644"
  become: true
  register: wordpress_nginx_config_result
  tags:
    - wordpress
    - nginx
    - templates

- name: Start Docker Compose services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_path }}"
    state: present # present (compose up), absent (compose down), stopped (compose stop), restarted (compose restart)
  become: true
  become_user: "{{ project_user }}"
  register: wordpress_compose_up_result
  tags:
    - wordpress
    - docker-compose
