services:
  ansible-controller:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    container_name: ansible_controller
    volumes:
      - ./ansible:/etc/ansible
    networks:
      - ansible_net
    tty: true
    tmpfs:
      - /tmp
      - /var/tmp
    command: /bin/bash -c "tail -f /dev/null"

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node1
    expose:
      - "22"
    networks:
      - ansible_net

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node2
    expose:
      - "22"
    networks:
      - ansible_net

networks:
  ansible_net:
    driver: bridge
